server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
#  hostname: test
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
